development:
  adapter: mysql2
  encoding: utf8
  database: rails
  pool: 5
  host: localhost
  username: rails
  password: jowto

production:
  adapter: mysql2
  database: rails
  host: localhost
  username: rails
  password: jowto
  encoding: utf8

